services:
  config-server:
    container_name: config-server
    image: eann1s/cloud-config-server:latest
    hostname: config-server
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8888:8888
    environment:
      - "CONFIG_LOCATION=https://github.com/Eann1S/config-repo"

  api-gateway:
    container_name: api-gateway
    image: eann1s/telegram-api-gateway:latest
    hostname: api-gateway
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8080:8080
    environment:
      DISCOVERY_SERVER_URL: discovery-server:8761
      CONFIG_SERVER_URL: config-server:8888
    depends_on:
      - discovery-server
      - config-server

  discovery-server:
    container_name: discovery-server
    image: eann1s/discovery-server:latest
    hostname: discovery-server
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8761:8761

  authentication-service:
    container_name: authentication-service
    image: eann1s/authentication-service:latest
    hostname: authentication-service
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8089:8089
    environment:
      SERVER_PORT: 8089
      DATABASE_URL: postgres:5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_URL: kafka:29092
      DISCOVERY_SERVER_URL: discovery-server:8761
      CONFIG_SERVER_URL: config-server:8888
    depends_on:
      - config-server
      - postgres
      - discovery-server
      - redis
      - kafka

  user-service:
    container_name: user-service
    image: eann1s/telegram-user-service:latest
    hostname: user-service
    restart: unless-stopped
    pull_policy: missing
    environment:
      DATABASE_URL: neo4j:7687
      KAFKA_URL: kafka:29092
      DISCOVERY_SERVER_URL: discovery-server:8761
      CONFIG_SERVER_URL: config-server:8888
    depends_on:
      - config-server
      - neo4j
      - discovery-server
      - kafka

  message-service:
    container_name: message-service
    image: eann1s/telegram-message-service:latest
    hostname: message-service
    restart: unless-stopped
    pull_policy: missing
    environment:
      DATABASE_HOST: cassandra
      DATABASE_PORT: 9042
      DATABASE_USERNAME: cassandra
      DATABASE_PASSWORD: cassandra
      DISCOVERY_SERVER_URL: discovery-server:8761
      CONFIG_SERVER_URL: config-server:8888
    depends_on:
      - config-server
      - cassandra
      - discovery-server

  postgres:
    container_name: postgres
    image: postgres:alpine3.17
    hostname: postgres
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: authentication-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  neo4j:
    container_name: neo4j
    image: neo4j:ubi8
    hostname: neo4j
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data/neo4j

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    hostname: cassandra
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/data/cassandra

  redis:
    container_name: redis
    image: redis:7.2-rc-alpine3.18
    hostname: redis
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 6379:6379

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  postgres-data: {}
  neo4j-data: {}
  cassandra-data: {}
