server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://${CONFIG_SERVER_URL:localhost:8888}
      retry:
        max-attempts: 10
        multiplier: 1.2
        initial-interval: 2000
        max-interval: 5000
