server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: user-service
  neo4j:
    uri: ${DATABASE_URL:localhost:7687}
    authentication:
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    retry:
      topic:
        enabled: true

logging:
  level:
    org:
      springframework:
        data:
          neo4j: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_URL:localhost:8761}/eureka

kafka:
  topics:
    authentication-service:
      consumer: authentication-service-consumer-topic
      producer: authentication-service-producer-topic

services:
  authentication-service:
    name: authentication-service
